### ISSUE TITLE
Sparta always crashes when I upload my own HRTF

### ISSUE THREAD

**Issue by Wenkang-Liu** [leomccormack/SPARTA#59] opened 2022-05-11 12:34 UTC
Hi,
Some of the sparta VSTs always crashed when I uploaded my own HRTF. However, it works well when I use the default HRTF.
I will be appreciate that you could help me to chekck it out what is the thing that makes the failure.
I made my HRTF based on mesh2hrtf.[https://sourceforge.net/p/mesh2hrtf/wiki/Tutorials/](url)  I believe I am not the only one with this problem.
And this is the sofa file.
 [HRIR_ARI_48000.zip](https://github.com/leomccormack/SPARTA/files/8669881/HRIR_ARI_48000.zip)
Looking forward to hear from you.
BR,
Wenkang

**Comment by leomccormack** [comment] 2022-05-18 10:20
Hi,
Can you please provide some more information regarding the plugin versions (on top banner), your OS, OS version, the DAW you are using, and which plugins specifically have the issue (and also which don't)? This will help narrow the problem down.

On my MacOS 10.15 machine, using Reaper v6.51, all of the sparta, compass, cropac, and hodirac plugins are able to load the 1550 HRIRs in the provided SOFA file.

If possible, please also provide a crash log. 

Many thanks!
Leo

**Comment by SDX-LV** [comment] 2022-05-18 21:20
Hello Leo,

Thank you for checking this. I can confirm that Wenkang's simulated HRTF was crashing 100% of times on one more Windows 10 PC running one of the latest Reaper versions and the latest SPARTA Binauralizer. Every time I tried to load it, Reaper crashed, while the default HRTF works fine.

In fact I had problems that Binauralizer crashes (already previos release version) when loading other Mesh2HRTF simulated SOFA files for a while (maybe it was always like this). In my experience I have about 40% chance of Binauralizer crashing when opening Mesh2HRTF SOFAfile. It happens during the opening of the SOFA file. If it manages to load, then it works great, but during loading it is dangerous. It happens equally often when using Reaper or VSTHost. Also it crashes especially reliably if Binauralizer tries to load the custom HRTF directly as it is opened. 
I even had cases with both Reaper and VSTHost where they got into an endless crash-loop where they try to re-load previous VST configuration and that causes Binauralizer to crash while loading custom HRTF. 

My wild guess is that Mesh2HRTF normalizes HRIR quite close to 0 dB, so perhaps some value gets out of range? Or maybe it is just something with memory management, because the crash is most likely if the SOFA is loaded automatically when Binauralizer reloads its previous configuration.

Either way, I would be happy to show you a demonstration of this crash in Reaper over Teams video meeting, as well as provide other details. I think Binauralizer is the best audio renderer to use with Mesh2HRTF SOFA files, but this instability gets in a way on Windows. 

Best Regards,
Sergejs

**Comment by leomccormack** [comment] 2022-05-31 11:55
OK! I think I've fixed the bug. Thank you for bringing this to my attention. It was related to a memory overflow when the HRIR length was not a multiple of 128. 
I'll push a new release in June. 

I'm closing this issue, but feel free to reopen it if the problem persists. 

Thanks again :)

**Closed by leomccormack** 2022-05-31 11:55 UTC
